### ISSUE TITLE
HTTPS protocol matching

### ISSUE THREAD

**Issue by DavidMikeSimon** [BYU-ARCLITE/Ayamel.js#4]
When running on a secure page, Ayamel.js needs to retrieve resources using HTTPS; otherwise, many browsers (e.g. Chrome) will complain and block the connection.

**Comment by gliese1337** [comment]
Currently Ayamel.js only fetches resources from URLs passed in to it from outside (e.g., from the Resource Library). I don't think it's terribly necessary to take on the responsibility of ensuring that those URLs are sanitized for HTTPS.

Wherever we might have hard-coded or internally-generated URLs, though, we should use protocol matching if at all possible.
